### ISSUE TITLE
Crash when running with android 19

### ISSUE THREAD

**Issue by DongNHJVS** [okta/okta-oidc-android#118]
I have test api with multi device. But in android 19 (4.4) i have error as below there : 

java.lang.VerifyError: com/okta/oidc/storage/OktaRepository
	at com.okta.oidc.clients.AuthAPI.<init>(AuthAPI.java:69)
	at com.okta.oidc.clients.web.SyncWebAuthClientImpl.<init>(SyncWebAuthClientImpl.java:93)
	at com.okta.oidc.clients.web.SyncWebAuthClientFactory.createClient(SyncWebAuthClientFactory.java:48)
	at com.okta.oidc.clients.web.WebAuthClientImpl.<init>(WebAuthClientImpl.java:61)
	at com.okta.oidc.clients.web.WebAuthClientFactory.createClient(WebAuthClientFactory.java:55)
	at com.okta.oidc.clients.web.WebAuthClientFactory.createClient(WebAuthClientFactory.java:32)
	at com.okta.oidc.OktaBuilder.createAuthClient(OktaBuilder.java:200)
	at com.okta.oidc.Okta$WebAuthBuilder.create(Okta.java:95)
	at com.seldatdirect.sel2b.talron.ui.activity.auth.login.LoginActivity.onContentViewCreated(LoginActivity.kt:90)
	at com.seldatdirect.dms.core.ui.activity.DMSBindingActivity.getLayoutResId(DMSBindingActivity.kt:29)
	at com.seldatdirect.dms.core.ui.activity.DMSActivity.onCreate(DMSActivity.kt:86)
	at android.app.Activity.performCreate(Activity.java:5243)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:184)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2140)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2226)
	at android.app.ActivityThread.access$700(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4998)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
	at dalvik.system.NativeStart.main(Native Method)

Device : sony table z
Android : 4.4
Otka version : 1.0.5
Tks.

**Comment by RMDYMathias** [comment]
I am having a similar crash on api 19 on an emulator:
java.lang.VerifyError: com/okta/authn/sdk/impl/client/DefaultAuthenticationClient

**Comment by FeiChen-okta** [comment]
@RMDYMathias This is caused by using API 19 with custom sign in. The auth-java SDK is using Java and this is not supported in API 19.
See the following [notes](https://github.com/okta/okta-oidc-android#Sign-in-with-your-own-UI)

We have a separate library that uses bazel to make the auth-java library compatible with Java 7.
In the future this will be handled by [Android Studio](https://developer.android.com/studio/preview/features#j8-desugar)

**Comment by FeiChen-okta** [comment]
@DongNHJVS Does this happen with the sample app? Check your build.gradle to see if multidex is enabled and if the gradle files are similar with the target and compile sdk.

**Comment by RMDYMathias** [comment]
@FeiChen-okta, I am already using the correct libraries for this.
![image](https://user-images.githubusercontent.com/57358772/68379711-ad9c4d00-014e-11ea-8f23-e058a13cccc1.png)
![image](https://user-images.githubusercontent.com/57358772/68379752-bb51d280-014e-11ea-9e0c-31182007364b.png)

**Comment by DongNHJVS** [comment]
@FeiChen-okta Hi,  I have not checked if the sample app is similar to my app.
My app have use multiDex and gradle is similar with sample app and my app use java 8.

**Comment by FeiChen-okta** [comment]
@DongNHJVS I have a PR open to fix this issue. some testing is needed.
https://github.com/okta/okta-oidc-android/pull/119

@RMDYMathias Your issue might be different. If the okta-authn-sdk is still failing, it could be due to java version I'm using to create the library is different from what you have installed. In this case I would suggest to try Android Studio preview as it creates Java7 compatible libraries during compilation it won't' have any mismatch versions. so you'll use:

```gradle
    implementation 'com.okta.authn.sdk:okta-authn-sdk-api:1.0.0'
    implementation('com.okta.authn.sdk:okta-authn-sdk-impl:1.0.0') {
        exclude group: 'com.okta.sdk', module: 'okta-sdk-httpclient'
    }
```

**Comment by DongNHJVS** [comment]
@FeiChen-okta tks for your help.

**Comment by RocketFuelAdmin** [comment]
@FeiChen-okta This is kind of an urgent matter, Is it possible to fast track the update into a new version ?

**Comment by FeiChen-okta** [comment]
@RocketFuelAdmin 1.0.6 released should fix the issue.
