### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by MathiasCochet** [okta/okta-oidc-android#122]
Hey all,

When using Proguard in combination with the Okta libraries (jar files) I keep getting the same error. I currently use there proguard rules:

`-keep class com.okta.** { *; }
-keep interface com.okta.** { *; }
-keep enum com.okta.** { *; }`

And this is the error I get: 

`com.okta.commons.lang.InstantiationException: Unable to instantiate instance with constructor [public com.okta.authn.sdk.impl.resource.DefaultAuthenticationRequest(com.okta.sdk.impl.ds.InternalDataStore)]
        at com.okta.commons.lang.Classes.instantiate(:193)
        at com.okta.sdk.impl.ds.DefaultResourceFactory.instantiate(:84)
        at com.okta.sdk.impl.ds.DefaultDataStore.instantiate(:141)
        at com.okta.sdk.impl.client.BaseClient.instantiate(:134)
        at be.xxxx.service.yyy.accounts.okta.OktaLoginServiceImpl.ˋ(:52)
        at be.xxxx.fragments.LoginFragment.ʻ(:476)
        at be.xxxx.fragments.LoginFragment.ˋ(:444)
        at be.xxxx.fragments.LoginFragment.onLoginButtonClicked(:313)
        at be.xxxx.fragments.LoginFragment_ViewBinding$4.ˎ(:38)
        at o.ŀƗ.onClick(:18)
        at android.view.View.performClick(View.java:6256)
        at android.view.View.onKeyUp(View.java:12419)
        at android.widget.TextView.onKeyUp(TextView.java:7473)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2715)
        at android.view.View.dispatchKeyEvent(View.java:11662)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:437)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1818)
        at o.Ɩɩ.ˋ(:1130)
        at o.ɹı.dispatchKeyEvent(:133)
        at o.con.dispatchKeyEvent(:535)
        at o.ʅ.dispatchKeyEvent(:59)
        at o.ӏ$if.dispatchKeyEvent(:2533)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:351)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4714)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4586)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4274)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4331)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4307)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4468)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2435)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1998)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1989)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2412)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6541)`

**Comment by MathiasCochet** [comment]
I found the problem.

I needed to add this rule to my proguard file:
-keep class j$.util.** { *; }

It might be a good idea to add these kind of things to the readme, that would have saved me a lot of time.
