### ISSUE TITLE
Debugging - {"type":4,"code":5003,"error":"Keys are invalid. null"}

### ISSUE THREAD

**Issue by mdeveracoding** [okta/okta-oidc-android#144]
All,

Within production, we are seeing application crashes being reported to back to our backend system called, "Glassbox".  Please see below (Crashed Thread main).  The error indicates two possible events that may be causing a "keys are invalid" exception. One ....the user maybe uninstalling and reinstalling our application then tries to login after a fresh install.  Second ....the user maybe changing their locking capabilities from PIN to Pattern.

Within my development environment I'm trying to get the Keys are invalid exception to trigger.  However, I'm not able to reproduce the exception even after a reinstall of our application and after changing my lock feature from PIN to pattern.

The device that is throwing a Keys are invalid exception in production is a Pixel 3XL with Android OS 10.  This is the same device that I'm trying to use in my development environment.

Is there a way to reproduce the problem that we are seeing in production but in development?

FYI....according to your docs the Keys are invalid exception should be handled by clearing sessionClient.  Because of this, I have wrapped a try catch around signin from authClient and around the callback onSuccess.  I did this because the exception being sent to our glassbox system shows a stack trace starting from onSuccess (see Crashed Thread main below).  My wrapper and code to clear sessionClient is way below.  However, I can't test my try catch wrapper since I can't replicate the keys are invalid exception error in development.  If I can't get the Keys are invalid exception to occur in my development environment then would my try catch wrapper still work?

Thanks for any assistance!

Crashed Thread main
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	... 1 more
Caused by: AuthorizationException: {"type":4,"code":5003,"error":"Keys are invalid. null"}
	at com.okta.oidc.util.AuthorizationException$EncryptionErrors.byEncryptionException(AuthorizationException.java:514)
	at com.okta.oidc.clients.sessions.SyncSessionClientImpl.getTokens(SyncSessionClientImpl.java:207)
	at com.okta.oidc.clients.sessions.SessionClientImpl.getTokens(SessionClientImpl.java:108)
	at com.amicamobile.authentication.AuthenticationModule$getTokens$1.onSuccess(AuthenticationModule.kt:214)
	at com.amicamobile.authentication.AuthenticationModule$getTokens$1.onSuccess(AuthenticationModule.kt:210)
	at com.okta.oidc.clients.AuthClientImpl.lambda$null$0(AuthClientImpl.java:72)
	at com.okta.oidc.clients.-$$Lambda$AuthClientImpl$YLKA2acDbflJH_fn8bDVG4-_xeA.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	... 3 more

Code with try catch wrapper....

     fun setRejectResponse (code: String, message: String, okta_type: String, okta_code: String, 
     okta_message: String, map: WritableMap, promise: Promise) {

        var sessionClient = _sessionClient
        if(sessionClient != null){
            sessionClient!!.clear()
        }
        map.putString("code", code)
        map.putString("message", message)
        map.putString("okta_type", okta_type)
        map.putString("okta_code", okta_code)
        map.putString("okta_message", okta_message)
        promise.reject(code, message, map)

    }

    fun getTokens(oktaConfigSetting: oktaConfigModel, promise: Promise) {

        val map = WritableNativeMap()

        try {

            _config = OIDCConfig.Builder().clientId(oktaConfigSetting.clientId!!)
                    .redirectUri(oktaConfigSetting.redirectUrl!!).endSessionRedirectUri(oktaConfigSetting.redirectUrl)
                    .discoveryUri(oktaConfigSetting.issuer!!).scopes(oktaConfigSetting.scopes!!)
                    .create()

            _authClient = Okta.AuthBuilder().withConfig(_config!!).withContext(_context)
                    .setRequireHardwareBackedKeyStore(!isEmulator())
                    .withStorage(SharedPreferenceStorage(_context)).create()

            _sessionClient = _authClient!!.sessionClient

            try {

                _authClient!!.signIn(_sessionToken, null, object : RequestCallback<Result, AuthorizationException> {

                    override fun onSuccess(result: Result) {

                        val tokens = _sessionClient!!.tokens
                        _accessToken = tokens.accessToken
                        _refreshToken = tokens.refreshToken
                        map.putString("accessToken", _accessToken)
                        map.putString("refreshToken", _refreshToken)
                        promise.resolve(map)
                        Log.d(_SUCCESSLOGIN, tokens.toString())

                    }

                    override fun onError(error: String, exception: AuthorizationException) {

                        setRejectResponse(_ERROR, error, exception.type.toString(), exception.code.toString(), exception.message.toString(), map, promise)

                    }

                })} catch (exception: AuthorizationException) {
                    setRejectResponse(_ERROR, exception.message.toString(), exception.type.toString(), exception.code.toString(), exception.message.toString(), map, promise)
                }

        } catch (exception: Exception) {

            setRejectResponse(_ERROR, exception.message.toString(), "n/a", "n/a", "n/a", map, promise)

        }

    }

**Comment by FeiChen-okta** [comment]
Hi @mdeveracoding Do you know which library version that this crash occurs? The latest library fixed a strong box encryption issue which seems to be related. Changing the PIN or adding a new fingerprint should invalidate all the keys. You can attempt to try that and see if the issue can be reproduced.

**Comment by mdeveracoding** [comment]
@FeiChen-okta, I'm using the following libraries, which can be found in our app build.gradle file.
Should I upgrade?

implementation 'com.okta.android:oidc-androidx:1.0.3'
implementation 'com.okta.authn.sdk:okta-authn-sdk-api:0.4.0'
implementation 'com.okta.authn.sdk:okta-authn-sdk-impl:0.4.0'
implementation 'com.okta.sdk:okta-sdk-okhttp:1.5.2'

**Comment by FeiChen-okta** [comment]
@mdeveracoding Yes you should definitely update. the current oidc-androidx version is 1.0.9, this have a fix for the Pixel 3 issue. As for the okta-authn-sdk 1.0.0 release was made.

**Comment by mdeveracoding** [comment]
@FeiChen-okta just to clarify do I replace....

implementation 'com.okta.authn.sdk:okta-authn-sdk-api:0.4.0'
implementation 'com.okta.authn.sdk:okta-authn-sdk-impl:0.4.0'

with....

implementation 'com.okta.authn.sdk:okta-authn-sdk-api:1.0.0'
implementation 'com.okta.authn.sdk:okta-authn-sdk-impl:1.0.0'

**Comment by FeiChen-okta** [comment]
I have this in my sample app:

```gradle
    implementation 'com.okta.authn.sdk:okta-authn-sdk-api:1.0.0'
    implementation('com.okta.authn.sdk:okta-authn-sdk-impl:1.0.0') {
        exclude group: 'com.okta.sdk', module: 'okta-sdk-httpclient'
    }
    implementation 'com.okta.sdk:okta-sdk-okhttp:1.5.4'
```

**Comment by mdeveracoding** [comment]
@FeiChen-okta ....thank you! I will mimic your sample app!

**Comment by mdeveracoding** [comment]
@FeiChen-okta the below is what I now have in our build gradle....

    implementation 'com.okta.android:oidc-androidx:1.0.9'
    implementation 'com.okta.authn.sdk:okta-authn-sdk-api:1.0.0'
    implementation('com.okta.authn.sdk:okta-authn-sdk-impl:1.0.0') {
        exclude group: 'com.okta.sdk', module: 'okta-sdk-httpclient'
    }
    implementation 'com.okta.sdk:okta-sdk-okhttp:1.5.4'

However, I still can't get the exception thrown regarding "Keys are invalid."  I have changed my PIN to a different value.  In addition, I added a new finger print to unlock my phone.  I'm trying to replicate the "Keys are invalid" issue to validate my try catch and the clearing of the sessionClient. I'm using my Pixel 3 XL with Android OS 10 while in debug mode and with a USB connection.  Is this not a correct to do testing?

**Comment by FeiChen-okta** [comment]
@mdeveracoding This is the correct behavior. `setInvalidatedByBiometricEnrollment` have been disabled so the keys are not invalidated on new pin/fingerprint. However disabling all lock screen  should invalidate all keys regardless of that option. You can use that to test.

**Comment by mdeveracoding** [comment]
@FeiChen-okta I totally disabled lock screen on my Pixel 3 XL.  And I still can't get the exception to occur.  I do really want to validate my fix and make the Keys are invalid occur.  Is there another setting or method that I can use to make the Keys are invalid to occur.

**Comment by FeiChen-okta** [comment]
@mdeveracoding My mistake the behavior I described is if userAuthenticationRequired is enabled. The current default implementation does not have this set. So the keys won't be invalidated even if the screen lock is disabled.

**Comment by mdeveracoding** [comment]
@FeiChen-okta Thanks so much for the clarification!  Is setting userAuthenticationRequired done in a file called, "StoreCredentialsModule.kt"?  I see function called, "setUserAuthenticationRequired" within this file and I can set this to true.  Is the correct place to set userAuthenticationRequired?

**Comment by FeiChen-okta** [comment]
@mdeveracoding The default implementation does not implement userAuthentication as this requires the developer to implement a UI to ask for fingerprint or pin. We have a example of implementing this https://github.com/okta/samples-android/tree/master/sign-in-kotlin
But you'll have to override the default encryption used.

**Comment by mdeveracoding** [comment]
@FeiChen-okta we do have a custom UI for authentication asking for pin or fingerprint. We just don't know how to make the exception of "Keys are invalid" to occur. We want this exception to occur so we can test our try catch. How do you make the exception "keys are invalid" to occur in development? Keep in mind we see these exceptions in production but not in development.

**Comment by FeiChen-okta** [comment]
@mdeveracoding I don't think you will get these exceptions in production since you've updated to the latest SDK. Are you trying to test the older SDK?

**Comment by JayNewstrom** [comment]
Closing due to inactivity. If you're able to recreate with the latest SDK, please comment and I can reopen. Thanks!
