### ISSUE TITLE
 AuthorizationException: 

### ISSUE THREAD

**Issue by gopalp1709** [okta/okta-oidc-android#153]
AuthorizationException: {"type":4,"code":4001,"error":"invalid_redirect_uri","errorDescription":"No uri registered to handle redirect or multiple applications registered"}
        at com.okta.oidc.clients.web.SyncWebAuthClientImpl.signIn(SyncWebAuthClientImpl.java:213)
        at com.okta.oidc.clients.web.WebAuthClientImpl.lambda$signIn$3$WebAuthClientImpl(WebAuthClientImpl.java:149)
        at com.okta.oidc.clients.web.-$$Lambda$WebAuthClientImpl$kahhJuT9U83XTCISiIUdYE87NJA.run(Unknown Source:6)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

I am getting above error while using the okta but sample app works fine is it because my android application project have flavors. I have created new app in okta console and pointed my android application but still getting above error. How to use android.defaultConfig.manifestPlaceholders = [
        'appAuthRedirectScheme': "com.***.***-stgone"] with flavors.
My current code is     productFlavors {
stg1{
manifestPlaceholders = [
        'appAuthRedirectScheme': "com.***.***-stgone"] 
}}

**Comment by FeiChen-okta** [comment]
Since you've got it working for the sample app. I think your current app is using the same uri as the sample app, try uninstalling the sample app. 
If both applications uses the same redirect uri then it will show that error.

**Comment by gopalp1709** [comment]
I have created another app and new uri still getting the same error.

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by FeiChen-okta** [comment]
Hi @gopalp1709 Check your redirectUri and endSessionRedirectUri. It should match the one you set in your admin console.

**Comment by gopalp1709** [comment]
Hi Team,

I am using login redirect uri ,logout redirect uri for redirectUri and endSessionRedirectUri respectively from console.
But still getting the same error , I did some debugging below methods return false.

private boolean isRedirectUrisRegistered(@NonNull Uri uri, Activity activity) {
    PackageManager pm = activity.getPackageManager();
    List<ResolveInfo> resolveInfos = null;
    if (pm != null) {
        Intent intent = new Intent();
        intent.setAction(Intent.ACTION_VIEW);
        intent.addCategory(Intent.CATEGORY_BROWSABLE);
        intent.setData(uri);
        resolveInfos = pm.queryIntentActivities(intent, PackageManager.GET_RESOLVED_FILTER);
    }
    boolean found = false;
    if (resolveInfos != null) {
        for (ResolveInfo info : resolveInfos) {
            ActivityInfo activityInfo = info.activityInfo;
            if (activityInfo.name.equals(OktaRedirectActivity.class.getCanonicalName()) &&
                    activityInfo.packageName.equals(activity.getPackageName())) {
                found = true;
            } else {
                Log.w(TAG, "Warning! Multiple " +
                        "applications found registered with same scheme");
                //Another installed app have same url scheme.
                //return false as if no activity found to prevent hijacking of redirect.
                return false;
            }
        }
    }


Thanks
Amol

**Comment by FeiChen-okta** [comment]
Hi @gopalp1709 Here is what my admin consoles look like:
![Screen Shot 2020-04-09 at 1 00 13 PM](https://user-images.githubusercontent.com/46411069/78935794-46b6f300-7a62-11ea-9c04-53bd0e2a10d3.png)

config.json:
```json
{
  "client_id": "<client id>",
  "redirect_uri": "com.oidc.sdk.sample:/callback",
  "end_session_redirect_uri": "com.oidc.sdk.sample:/logout",
  "scopes": [
    "openid",
    "profile",
    "email"
  ],
  "discovery_uri": "<discovery uri>"
}
```

manifest scheme in build.gradle:
```gradle
        manifestPlaceholders = [
                "appAuthRedirectScheme": "com.oidc.sdk.sample"
        ]
```

Make sure your settings are similar and that should work.

**Comment by gopalp1709** [comment]
Hi Team,
I am using suggested configuration and also analyzed the generated android manifest file .
Manifest file contains the OktaAuthenticationActivity ,OktaRecivierActivity and mentioned redirect Uri but still getting same error.

Thanks
Amol

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by FeiChen-okta** [comment]
Run this command to see if the scheme set: `adb shell dumpsys package yourPackageName`
you should see something like 
```text
Activity Resolver Table:
  Schemes:
      com.oidc.sdk.sample:
        773983c com.okta.oidc.example/com.okta.oidc.OktaRedirectActivity filter 6d98037
          Action: "android.intent.action.VIEW"
          Category: "android.intent.category.DEFAULT"
          Category: "android.intent.category.BROWSABLE"
          Scheme: "com.oidc.sdk.sample"
``` 

Then run `adb shell pm query-activities -a android.intent.action.VIEW -d "com.oidc.sdk.sample://"`
Replace the scheme `com.oidc.sdk.sample` with the one from the previous command.
This should only list one activity.

**Comment by gopalp1709** [comment]
Created the fresh application in OKTA console and it's working now. 
Thanks
Amol

**Comment by noelstieglitz** [comment]
H, @FeiChen-okta,
I'm seeing the same error, with a similar situation - everything works in the sample apps, but I'm getting the above error when trying to integrate it into my app.  I have made sure the sample app was removed.  

You mentioned that running `run adb shell pm query-activities -a android.intent.action.VIEW -d "com.oidc.sdk.sample://"` should return only one activity.  
I see two activities listed:

`  Activity #0:
    priority=0 preferredOrder=0 match=0x208000 specificIndex=-1 isDefault=true
    ActivityInfo:
      name=com.okta.oidc.OktaRedirectActivity
      packageName=mypackage.debug
      enabled=true exported=true directBootAware=false
      taskAffinity=mypackage.debug targetActivity=null persistableMode=PERSIST_ROOT_ONLY
      launchMode=0 flags=0x302200 privateFlags=0x0 theme=0x0
      screenOrientation=-1 configChanges=0x3 softInputMode=0x0
      lockTaskLaunchMode=LOCK_TASK_LAUNCH_MODE_DEFAULT
      resizeMode=RESIZE_MODE_RESIZEABLE_VIA_SDK_VERSION
      ApplicationInfo:
        name=com.mypackage.MainApplication
        packageName=mypackage.debug
        labelRes=0x7f12002f nonLocalizedLabel=null icon=0x7f0e0000 banner=0x0
        className=mypackage.MainApplication
        processName=mypackage.debug
        taskAffinity=mypackage.debug
        uid=10136 flags=0x30c83f46 privateFlags=0xc801110 theme=0x7f130008
        requiresSmallestWidthDp=0 compatibleWidthLimitDp=0 largestWidthLimitDp=0
        sourceDir=/data/app/mypackage.debug-PdqlQ70v_ny9yiD8ar5eHQ==/base.apk
        resourceDirs=[/product/overlay/DisplayCutoutEmulationEmu01/DisplayCutoutEmulationEmu01Overlay.apk]
        seinfo=default:targetSdkVersion=29
        seinfoUser=:complete
        dataDir=/data/user/0/mypackage.debug
        deviceProtectedDataDir=/data/user_de/0/mypackage.debug
        credentialProtectedDataDir=/data/user/0/mypackage.debug
        enabled=true minSdkVersion=23 targetSdkVersion=29 versionCode=38 targetSandboxVersion=1
        supportsRtl=true
        fullBackupContent=true
        networkSecurityConfigRes=0x7f160003
        HiddenApiEnforcementPolicy=2
        usesNonSdkApi=false
        allowsPlaybackCapture=true
  Activity #1:
    priority=0 preferredOrder=0 match=0x208000 specificIndex=-1 isDefault=true
    ActivityInfo:
      name=net.openid.appauth.RedirectUriReceiverActivity
      packageName=mypackage.debug
      enabled=true exported=true directBootAware=false
      taskAffinity=mypackage.debug targetActivity=null persistableMode=PERSIST_ROOT_ONLY
      launchMode=0 flags=0x300200 privateFlags=0x0 theme=0x0
      screenOrientation=-1 configChanges=0x3 softInputMode=0x0
      lockTaskLaunchMode=LOCK_TASK_LAUNCH_MODE_DEFAULT
      resizeMode=RESIZE_MODE_RESIZEABLE_VIA_SDK_VERSION
      ApplicationInfo:
        name=mypackage.MainApplication
        packageName=mypackage.debug
        labelRes=0x7f12002f nonLocalizedLabel=null icon=0x7f0e0000 banner=0x0
        className=mypackage.MainApplication
        processName=mypackage.debug
        taskAffinity=mypackage.debug
        uid=10136 flags=0x30c83f46 privateFlags=0xc801110 theme=0x7f130008
        requiresSmallestWidthDp=0 compatibleWidthLimitDp=0 largestWidthLimitDp=0
        sourceDir=/data/app/mypackage.debug-PdqlQ70v_ny9yiD8ar5eHQ==/base.apk
        resourceDirs=[/product/overlay/DisplayCutoutEmulationEmu01/DisplayCutoutEmulationEmu01Overlay.apk]
        seinfo=default:targetSdkVersion=29
        seinfoUser=:complete
        dataDir=/data/user/0/mypackage.debug
        deviceProtectedDataDir=/data/user_de/0/mypackage.debug
        credentialProtectedDataDir=/data/user/0/mypackage.debug
        enabled=true minSdkVersion=23 targetSdkVersion=29 versionCode=38 targetSandboxVersion=1
        supportsRtl=true
        fullBackupContent=true
        networkSecurityConfigRes=0x7f160003
        HiddenApiEnforcementPolicy=2
        usesNonSdkApi=false
        allowsPlaybackCapture=true
`
Any thoughts on how I can track down the issue?

**Comment by JayNewstrom** [comment]
@noelstieglitz make sure you've uninstalled all other Okta sample apps. You can only have one sample app installed with the same redirect url.

**Comment by noelstieglitz** [comment]
@JayNewstrom thanks for the quick response.  yes, I was careful to ensure only the current app I was testing was installed so there wouldn't be multiple apps with the same URI.  Note in the above output that neither of the Activities listed are part of my app:
`com.okta.oidc.OktaRedirectActivity`
and
`net.openid.appauth.RedirectUriReceiverActivity`

**Comment by JayNewstrom** [comment]
The Okta one is the one acting on behalf of the sample.

Looks like the other is from here: https://github.com/openid/AppAuth-Android

Can you uninstall the other sample app?

**Comment by noelstieglitz** [comment]
Unfortunately, there is no sample app installed.  Both activities are from my app (note the `packageName=mypackage.debug` for both activities, which is sanitized version of the real app name).

**Comment by JayNewstrom** [comment]
Are you including the linked library in your app as well? For instance `implementation 'net.openid:appauth:0.8.1'`

**Comment by noelstieglitz** [comment]
Not directly but I am including `implementation 'com.okta.android:appauth-android:0.1.0'`.  Perhaps that uses the `net.openid:appauth` library?

**Comment by noelstieglitz** [comment]
That's the issue!  I need to remove `implementation 'com.okta.android:appauth-android:0.1.0'`.  Thanks again, @JayNewstrom.

**Comment by JayNewstrom** [comment]
Glad we got it figured out 👍 Have a great day!
