### ISSUE TITLE
Error 1008 contains no helpful information

### ISSUE THREAD

**Issue by default-kramer** [okta/okta-oidc-android#168]
I just traced an problem in an Android app to this codebase and eventually got this stack trace:

```
"AuthorizationException: {"type":1,"code":1008}↵
    at com.okta.oidc.util.AuthorizationException$AuthorizationRequestErrors.<clinit>(AuthorizationException.java:301)↵
    at com.okta.oidc.clients.SyncAuthClientImpl.signIn(SyncAuthClientImpl.java:113)↵
    at com.okta.oidc.clients.AuthClientImpl.lambda$signIn$2$AuthClientImpl(AuthClientImpl.java:69)↵
    at com.okta.oidc.clients.-$$Lambda$AuthClientImpl$bd2LRazdR1NgrGeRE1VrsI8D_uI.run(Unknown Source:8)↵
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)↵
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)↵
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)↵
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)↵
    at java.lang.Thread.run(Thread.java:919)↵"
```

Which points to this line of code: https://github.com/okta/okta-oidc-android/blob/e9600e5bb77fd6d8cf932b14b5af04a58b23a3b5/library/src/main/java/com/okta/oidc/clients/SyncAuthClientImpl.java#L113

And now I'm pretty much stuck, because the original exception is being discarded. Can you please preserve the original exception somehow?

**Comment by FeiChen-okta** [comment]
Hi @default-kramer Agree that this is not helpful. The authorizationexception should wrap the original exception to preserve it.
