### ISSUE TITLE
SSLException Android 4.4 (API level 19) Chrome custom tab 

### ISSUE THREAD

**Issue by ngoluuduythai** [okta/okta-oidc-android#176]
I got this issue when try to run **okta chrome custom tab** example with **android level 19**

```
    AuthorizationException: {"type":0,"errorDescription":"SSL handshake aborted: ssl=0xb7dc3c70: I\/O error during system call, Connection reset by peer","code":0}
        at com.okta.oidc.net.request.ConfigurationRequest.executeRequest(ConfigurationRequest.java:68)
        at com.okta.oidc.clients.AuthAPI.obtainNewConfiguration(AuthAPI.java:101)
        at com.okta.oidc.clients.web.SyncWebAuthClientImpl.signIn(SyncWebAuthClientImpl.java:218)
        at com.okta.oidc.clients.web.WebAuthClientImpl.lambda$signIn$3$WebAuthClientImpl(WebAuthClientImpl.java:149)
        at com.okta.oidc.clients.web.-$$Lambda$WebAuthClientImpl$kahhJuT9U83XTCISiIUdYE87NJA.run(lambda)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
```

 ```
    Caused by: javax.net.ssl.SSLException: SSL handshake aborted: ssl=0xb7dc3c70: I/O error during system call, Connection reset by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
        at com.android.okhttp.Connection.connect(Connection.java:107)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
        at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
        at com.okta.oidc.net.HttpClientImpl.connect(HttpClientImpl.java:97)
        at com.okta.oidc.net.request.BaseRequest.openConnection(BaseRequest.java:58)
        at com.okta.oidc.net.request.ConfigurationRequest.executeRequest(ConfigurationRequest.java:60)
        at com.okta.oidc.clients.AuthAPI.obtainNewConfiguration(AuthAPI.java:101) 
        at com.okta.oidc.clients.web.SyncWebAuthClientImpl.signIn(SyncWebAuthClientImpl.java:218) 
        at com.okta.oidc.clients.web.WebAuthClientImpl.lambda$signIn$3$WebAuthClientImpl(WebAuthClientImpl.java:149) 
        at com.okta.oidc.clients.web.-$$Lambda$WebAuthClientImpl$kahhJuT9U83XTCISiIUdYE87NJA.run(lambda) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
```

**Comment by johndavidson-okta** [comment]
Hello @ngoluuduythai

Can you tell me a little bit about the Device/emulator you're using when you see this error?

**Comment by ngoluuduythai** [comment]
I use pixel C API 19, android 4.4 (simulator have google apis, cpu x86 ).

**Comment by FeiChen-okta** [comment]
Hi @ngoluuduythai That emulator doesn't have play store and doesn't come with chrome installed. How are you installing chrome or any other CCT compatible browser?

**Comment by ngoluuduythai** [comment]
I got a solution for that when I add Google Play Services Security Provider. It works normally now.
`        try {
            ProviderInstaller.installIfNeeded(applicationContext)

        } catch ( e: GooglePlayServicesRepairableException) {
            e.printStackTrace();
        } catch ( e: GooglePlayServicesNotAvailableException) {
            e.printStackTrace();
        }`
@FeiChen-okta I install chrome through apk file and it works.

**Comment by JayNewstrom** [comment]
Glad you got this working :)
