### ISSUE TITLE
Receiving: {"type":0,"code":3,"errorDescription":"Network error"} 

### ISSUE THREAD

**Issue by aminner** [okta/okta-oidc-android#179]
Hello! 

Our Okta integrated Android application up and running since November of last year, and all is mostly well. However, for some users (only a handful over many 10s of thousands, all on Samsungs so far), we're receiving the following error which has thus far been un-reproducable for us in our development testing. 
```
AuthorizationException: {"type":0,"code":3,"errorDescription":"Network error"} at 
com.okta.oidc.net.request.TokenRequest.executeRequest(TokenRequest.java:169) at 
com.okta.oidc.clients.SyncAuthClientImpl.signIn(SyncAuthClientImpl.java:104) at 
com.okta.oidc.clients.AuthClientImpl.lambda$signIn$2$AuthClientImpl(AuthClientImpl.java:69) at 
com.okta.oidc.clients.-$$Lambda$AuthClientImpl$bd2LRazdR1NgrGeRE1VrsI8D_uI.run(Unknown Source:8) at 
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919) 
Caused by: AuthorizationException: ***{"type":0,"code":9,"errorDescription":"Invalid ID Token"}*** at 
com.okta.oidc.OktaIdToken.validate(OktaIdToken.java:343) at 
com.okta.oidc.net.request.TokenRequest.executeRequest(TokenRequest.java:160) ... 8 more Caused by: 
java.lang.IllegalStateException: Issued at time is more than 10 minutes before or after the current time ... 10 more
```

Looking at the code it appears that this is generated by:
```
if (!"RS256".equals(mHeader.alg)) {
      throw AuthorizationException.fromTemplate(ID_TOKEN_VALIDATION_ERROR,
```

Is there any ways for us to mitigate this or fix it? There are users who just cannot seem to log in on our application and any leads would be greatly appreciated! 

Thank you!

**Comment by FeiChen-okta** [comment]
Hi @aminner This is the cause of the error
```
        if (Math.abs(nowInSeconds - mClaims.iat) > TEN_MINUTES_IN_SECONDS) {
            throw AuthorizationException.fromTemplate(ID_TOKEN_VALIDATION_ERROR,
                    AuthorizationException.TokenValidationError.createWrongTokenIssuedTime(
                            TEN_MINUTES_IN_SECONDS.intValue() / SECONDS_IN_ONE_MINUTE));
        }
```
This happens when the device time drifts past 10 mins. A solution would be to catch this error and ask the user to update the time and try again.

**Comment by aminner** [comment]
Thank you for getting back to me so quickly! This makes perfects sense I'll add that to our knowledge base for future reference.
