### ISSUE TITLE
Misleading error code: INVALID_DISCOVERY_DOCUMENT

### ISSUE THREAD

**Issue by broccolibird** [okta/okta-oidc-android#193]
Had a new developer joining the team who was having an issue logging into our application. The error code was `0`, leading us to INVALID_DISCOVERY_DOCUMENT. The actual issue was his emulator did not have an internet connection.

We are using these error codes to help customers when they have issues, so meaningful error codes are important to us. If nothing else, maybe this will serve as documentation for others with the same issue.

```
W/<redacted>: WARN  <redacted> - MainViewModel - login failed!
    com.okta.oidc.util.AuthorizationException: Unable to resolve host "<redacted>": No address associated with hostname
        at com.okta.oidc.net.request.ConfigurationRequest.executeRequest(ConfigurationRequest.java:68)
        at com.okta.oidc.clients.AuthAPI.obtainNewConfiguration(AuthAPI.java:101)
        at com.okta.oidc.clients.web.SyncWebAuthClientImpl.signIn(SyncWebAuthClientImpl.java:218)
        at com.<redacted>.MainActivity.lambda$onLaunchLoginEvent$10$MainActivity(MainActivity.java:521)
        at com.<redacted>.-$$Lambda$MainActivity$mVh-6PrCvwJKFoB2MRM6dcT0Zuk.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.net.UnknownHostException: Unable to resolve host "<redacted>": No address associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        at com.android.okhttp.Dns$1.lookup(Dns.java:41)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
        at com.okta.oidc.net.HttpClientImpl.connect(HttpClientImpl.java:97)
        at com.okta.oidc.net.request.BaseRequest.openConnection(BaseRequest.java:58)
        at com.okta.oidc.net.request.ConfigurationRequest.executeRequest(ConfigurationRequest.java:60)
        ... 9 common frames omitted
    Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at libcore.io.Linux.android_getaddrinfo(Native Method)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
        at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
```

**Comment by FeiChen-okta** [comment]
Hi @broccolibird thanks for the information will address this in the next release.
