### ISSUE TITLE
No compatible browser found when trying to login

### ISSUE THREAD

**Issue by martin-mori-globant** [okta/okta-oidc-android#235]
Hi, I have integrated the sdk on my app. 

Some users are unable to login through okta.

okta_version = '1.0.16'

This is how I initilize the web client:
`webClient = Okta.WebAuthBuilder()
                .withConfig(config)
                .withContext(context)
                .browserMatchAll(true)
                .setRequireHardwareBackedKeyStore(!disableHardwareBackedKeyStore)
                .withStorage(SharedPreferenceStorage(context))
                .create()`

Users are experiencing this error Im catching it on the Okta login ResultCallback:
`AuthorizationException: {"type":0,"code":10,"errorDescription":"No compatible browser found"}
at com.okta.oidc.AuthenticationResultHandler.handleAuthenticationResult(AuthenticationResultHandler.java:85)
at com.okta.oidc.AuthenticationResultHandler.onActivityResult(AuthenticationResultHandler.java:70)
at com.okta.oidc.OktaResultFragment.onActivityResult(OktaResultFragment.java:110)
at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
at android.app.Activity.dispatchActivityResult(Activity.java:8310)
at android.app.ActivityThread.deliverResults(ActivityThread.java:5002)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7660)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

Its weird because it seems to happen only to Pixel phone users.

**Comment by JayNewstrom** [comment]
Hi, thanks for reaching out.

Are you seeing this just in your crash reporting tool? Or are you able to reproduce this?

**Comment by martin-mori-globant** [comment]
I was able to reproduce it on a Pixel by setting up Opera as my default browser and then disabling Chrome.

With Opera set as my default browser but with Chrome enabled it works fine.

**Comment by JayNewstrom** [comment]
From what I've read, opera doesn't support chrome custom tabs. Which is what this SDK uses internally to implement OIDC (calling out to our sign in widget, and getting the redirect back into an app).

**Comment by martin-mori-globant** [comment]
I´m seeing its happening to many users (all Pixel users), and Pixel uses for default Chrome, so could it be any other reason this is happening? I don't think all of them have had Chrome disabled.

**Comment by JayNewstrom** [comment]
Internally, we look for https://github.com/okta/okta-oidc-android/blob/master/library/src/main/java/com/okta/oidc/util/AuthorizationException.java#L230 in the error callback, and display a message to the user.

I would recommend telling them to use chrome, as that's primarily what we test with.
If you can reproduce a scenario that you think should be supported, we'd be happy to take a look into supporting it.

**Comment by JayNewstrom** [comment]
@martin-mori-globant Please reopen if you have any more questions.
