### ISSUE TITLE
Android 11(API 30) Class not found when unmarshalling: com.okta.oidc.CustomTabOptions

### ISSUE THREAD

**Issue by adamshick-Skyward** [okta/okta-oidc-android#240]
Upgraded a Samsung Tab 6 to Android 11. The login process was working fine on Android 10. Once upgraded the following error cam up:

E/Parcel: Class not found when unmarshalling: com.okta.oidc.CustomTabOptions`
   java.lang.ClassNotFoundException: com.okta.oidc.CustomTabOptions
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3350)
        at android.os.Parcel.readParcelable(Parcel.java:3284)
        at android.os.Parcel.readValue(Parcel.java:3186)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getString(BaseBundle.java:1196)
        at android.content.Intent.getStringExtra(Intent.java:8889)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1128)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:894)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1710)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1560)
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1512)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1663)
        at android.os.Binder.execTransactInternal(Binder.java:1190)
        at android.os.Binder.execTransact(Binder.java:1159)
     Caused by: java.lang.ClassNotFoundException: com.okta.oidc.CustomTabOptions
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:3350) 
        at android.os.Parcel.readParcelable(Parcel.java:3284) 
        at android.os.Parcel.readValue(Parcel.java:3186) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3579) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.getString(BaseBundle.java:1196) 
        at android.content.Intent.getStringExtra(Intent.java:8889) 
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1128) 
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:894) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1710) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1560) 
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1512) 
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1663) 
        at android.os.Binder.execTransactInternal(Binder.java:1190) 
        at android.os.Binder.execTransact(Binder.java:1159) 

Along with this error:

` AuthorizationException: {"type":0,"code":10,"errorDescription":"No compatible browser found"}`

**Comment by JayNewstrom** [comment]
Hi @adamshick-Skyward looks like you might have a few issues here. Can you give us steps to recreate the issue? I'm able to log in successfully with Android 10/11.

**Comment by adamshick-Skyward** [comment]
It seems to only be happening on the tablet. Emulators and Samsung s10 s20 and s21 all work fine. I am going through the normal process of calling `webAuthClient.signIn(requireActivity(), null)` to start the login process.

**Comment by JayNewstrom** [comment]
This looks like it's going to be a difficult one to dig into. I don't have a Samsung Tab 6. If there's any way you can provide us more information, that would be great.

I've added an internal task to our backlog to look deeper into this. OKTA-404400

**Comment by adamshick-Skyward** [comment]
Sure thing. What info would you like to know?

Here is our setup for out config. Again this all works fine on a phone rocking Android 12(api 30):

val customConfig = CustomConfiguration.Builder()
            .tokenEndpoint(BuildConfig.skywardTokenEndpoint)
            .authorizationEndpoint(BuildConfig.skywardSSOUrl)
            .endSessionEndpoint(BuildConfig.skywardSSOLogoutUrl)
            .create()

        OIDCConfig.Builder()
            .clientId("OURCLIENTID")
            .redirectUri("skywardio://callback")
            .endSessionRedirectUri("skywardio://logoutCallback")
            .scopes(
                "openid",
                "email",
                "profile",
                "offline_access"
            )
            .customConfiguration(customConfig)
            .create()

**Comment by adamshick-Skyward** [comment]
Also just found out that it doesn't work on Phones on the new Android 12 Beta. Was tested on a Pixel 4

**Comment by JayNewstrom** [comment]
This might be a build issue on your end. `ClassNotFoundException` is suspect.

Can you recreate these issues in our sample app? https://github.com/okta/samples-android/tree/master/browser-sign-in

**Comment by JayNewstrom** [comment]
Can you confirm chrome is installed? We rely on Chrome custom tabs, which uses the chrome app.

**Comment by adamshick-Skyward** [comment]
The sample actual works fine when pointed to the same endpoints. I have been making sure my configs are setup to the same thing but our app still fails for some reason

**Comment by JayNewstrom** [comment]
What version of the Android gradle plugin are you using? We've seen reports of issues when using newer gradle plugin versions.

**Comment by adamshick-Skyward** [comment]
Both the sample and our app is rocking Gradle 4.1.2

**Comment by adamshick-Skyward** [comment]
I actually got the sample app now to say that there is no compatible browser after working for a while

**Comment by adamshick-Skyward** [comment]
I figured out the issue. It's when compileSdkVersion and targetSdkVersion are set to 30. Happens in both our app and the sample app

**Comment by adamshick-Skyward** [comment]
This issue seems to be similar what is happening even though it's 6 years old: https://stackoverflow.com/questions/28589509/android-e-parcel-class-not-found-when-unmarshalling-only-on-samsung-tab3/28589962

**Comment by JayNewstrom** [comment]
It appears like this is outside of our control, do you agree @adamshick-Skyward?

**Comment by adamshick-Skyward** [comment]
I think it's still your guys issue since in this sample: https://github.com/okta/samples-android/tree/master/browser-sign-in if it is set to compile on 30 instead of 29(The default you have it set t) it breaks your sample app

**Comment by JayNewstrom** [comment]
I've attempted one of the suggested fixes in the stackoverflow thread. See https://github.com/okta/okta-oidc-android/pull/244

Could you do me a favor and try it out? (I don't have access to the samsung tablet)

Add `maven { url "https://oss.sonatype.org/content/repositories/snapshots" }` to your build.gradle `repositories` block
Ensure you have added the dependency with the right version to your `dependencies` block: `com.okta.android:okta-oidc-android:1.0.20-SNAPSHOT`

**Comment by adamshick-Skyward** [comment]
Your change has fixed the issue on Samsung Tab s6 using compile 30 api!

**Comment by JayNewstrom** [comment]
Great! Thanks for confirming!

**Comment by JayNewstrom** [comment]
This is fixed in master. We will do a release soon.
