### ISSUE TITLE
Intermittent, silent crash in WebAuthClient.signin and logout

### ISSUE THREAD

**Issue by coreform** [okta/okta-oidc-android#253]
I have been seeing this problem for the past week on my Pixel 3 (API 30, Chrome version 91.0.4472.164) and have more recently had a report indicating similar symptoms from a user on a Samsung S8 (Samsung SM-G950F API 28, not sure of Chrome version). I believe Chrome 91 was released around a week ago so may correlate with these problems.

There is no crash or logs for the signin problem, I see my own logs reach the point just before the call into Okta-oidc-android (also for oidc-androidx). Both versions 1.0.18 and 1.0.20 (oidc-androix seems no longer supported there). This is the case whether or not targetSdkVersion=30|29.

WebAuthClient is setup as follows:

`return Okta.WebAuthBuilder()
            .withConfig(config)
            .withContext(activity)
            .supportedBrowsers(
                "com.android.chrome",
                "com.google.android.apps.chrome",
                "com.android.chrome.beta",
                "com.sec.android.app.sbrowser"
            )
            .setRequireHardwareBackedKeyStore(!isEmulator())
            .withStorage(SharedPreferenceStorage(context.applicationContext))
            .create()`

The Okta app is setup on both devices, when I use the same account on devices (and emulators) that do not have the Okta app installed I never observe these problems.

**Observed behaviour:**

Most often: The Okta lib acts as though it simply finishes with no callbacks invoked...
Very occasionally: It acts like it is expected to, callbacks are invoked, redirect yields the next step in the flow. It just so happens that in this app's case, this can succeed without even needing to Okta SDK's onActivityResult mechanism to work.

**Hypothesis:**

Chrome Browser for Android 91 update (but only for some devices) causes Okta SDK's onActivityResult mechanism to always fail.

I have also observed an intermittent exception upon WebAuthClient.signOut, which yields a catastrophic crash and in combination with the other problem with this SDK in that it leaves the CustomTab in the backstack, that CustomTab is seen to be logged into the website (such an unfortunate situation yielded by this lib!):

`2021-07-19 11:37:21.178 25913-25913/<redacted> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <redacted>, PID: 25913
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW pkg=com.android.chrome (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
        at android.app.Activity.startActivityForResult(Activity.java:5314)
        at android.app.Activity.startActivityForResult(Activity.java:5272)
        at android.app.Activity.startActivity(Activity.java:5658)
        at android.app.Activity.startActivity(Activity.java:5611)
        at com.okta.oidc.OktaAuthenticationActivity.onServiceConnected(OktaAuthenticationActivity.java:281)
        at com.okta.oidc.ServiceConnection.onCustomTabsServiceConnected(ServiceConnection.java:44)
        at androidx.browser.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:57)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1978)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2010)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by coreform** [comment]
Well I had turned on `Don't keep Activities` while testing something else and forgot about it. Not sure if that also explains the intermittent `No Activity found to handle Intent` on signOut though.

**Comment by NikitaAvraimov-okta** [comment]
Thanks for sharing this in such detail. I believe it is closely related to samsung device-related crashes, which we currently are investigating at OKTA-356435
