### ISSUE TITLE
NoSuchFieldError Excpetion after merge or update 

### ISSUE THREAD

**Issue by jempis** [okta/okta-oidc-android#70]
Hi All,
i have integrate the okta-oidc-android without problem, but when i merge with another branch 
(i use git) and i build the project return this error

```
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:174)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:115)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:122)
        at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.<init>(HttpClientRequestExecutor.java:138)
        at com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutorFactory.create(HttpClientRequestExecutorFactory.java:29)
        at com.okta.sdk.impl.client.BaseClient.createRequestExecutor(BaseClient.java:103)
        at com.okta.sdk.impl.client.BaseClient.<init>(BaseClient.java:72)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.<init>(DefaultAuthenticationClient.java:84)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClientBuilder.build(DefaultAuthenticationClientBuilder.java:212)
        at my.custom.app.okta.oktaInstance.init(oktaInstance.kt:427)
        at my.custom.app.okta.oktaInstance.access$initOkta(oktaInstance.kt:41)
        at my.custom.app.okta.oktaInstance$Companion.setConfigElements(oktaInstance.kt:89)
        at my.custom.app.OktaViewModel.saveParamenter(OktaViewModel.kt:25)
        at my.custom.app.OktaFragment.onData(OktaFragment.kt:156)
        at my.custom.app.OktaFragment.access$onConfigData(OktaFragment.kt:15)
        at my.custom.app.OktaFragment$setupObservers$4.onChanged(OktaFragment.kt:78)
        at my.custom.app.OktaFragment$setupObservers$4.onChanged(OktaFragment.kt:15)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at my.custom.app.OktaViewModel$doData$1.onResult(OktaViewModel.kt:87)
        at my.custom.app.OktaViewModel$dogData$1.onResult(OktaViewModel.kt:84)
        at my.custom.app.managers.resources.OktaViewModel$loadConfig$onResponse$1.run(ResourcesManager.kt:95)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-07-05 16:52:12.386 29131-29145/my.custom.app E/System: Uncaught exception thrown by finalizer
2019-07-05 16:52:12.389 29131-29145/my.custom.app E/System: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.concurrent.atomic.AtomicBoolean.compareAndSet(boolean, boolean)' on a null object reference
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.shutdown(PoolingHttpClientConnectionManager.java:393)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.finalize(PoolingHttpClientConnectionManager.java:206)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:764)
```

To remove this Exception I have to do a 'Clean Project' on Android Studio or 'Clear Cache' and 'Clear Storage' in the Device for the App.

The principal problem is that this error occurs when i update the app (i use the Beta by Crahslitycs ).

Can you help me Please

Thanks

**Comment by FeiChen-okta** [comment]
Hi @jempis It looks like you are using `okta-auth-java` to sign in instead of the browser.
Check your dependencies tree to see if other versions of
`org.apache.httpcomponents:httpclient:4.5.3`. is included.

If it is you can exclude one or you can try using okhttp for the auth-java sdk by replacing
```gradle
'com.okta.sdk:okta-sdk-httpclient:${okta.sdk.version}'
```
with

```gradle
'com.okta.sdk:okta-sdk-okhttp:${okta.sdk.version}'
```

**Comment by jempis** [comment]
Hi @FeiChen-okta,
thank's for response.
Yes i don't use the browser for authehtication.

I have already a dependencies with  `com.okta.sdk:okta-sdk-okhttp:1.4.1`

I don't have  dependencies for the library `org.apache.httpcomponents:httpclient` and when i implemented this library i have this error:
`Duplicate class org.apache.commons.logging.Log`

**Comment by FeiChen-okta** [comment]
Hi @jempis,

From the log: 
`com.okta.sdk.impl.http.httpclient.HttpClientRequestExecutor.<init>(HttpClientRequestExecutor.java:138)
`
the app is using apache httpclient. You mentioned that it works when you do a clean build but the issue happens after a merge? Can you clarify what you mean by that? Does the crash happens if you don't merge? Can you also Build->Analyze Apk and select the dex file to see the classes.

Also you can try the following Android recommendation to include apache client:
https://developer.android.com/about/versions/marshmallow/android-6.0-changes#behavior-apache-http-client

**Comment by FeiChen-okta** [comment]
@jempis can you try adding this to your gradle file
```gradle
    implementation 'com.okta.authn.sdk:okta-authn-sdk-api:1.0.0'
    implementation ('com.okta.authn.sdk:okta-authn-sdk-impl:1.0.0') {
        exclude group: 'com.okta.sdk', module:'okta-sdk-httpclient'
    }
    implementation 'com.okta.sdk:okta-sdk-okhttp:1.5.2'
```
