### ISSUE TITLE
WebAuthClient signin creating exception

### ISSUE THREAD

**Issue by pramodneyyoor** [okta/okta-oidc-android#99]
When the following method is called to open up the Chrome widget mWebAuth.signIn(this, mPayload); I get the following exception:
AuthorizationException: {"type":4,"code":5003,"error":"Keys are invalid. null"}

![image](https://user-images.githubusercontent.com/36133452/65087415-92e5fd00-d983-11e9-83d5-19d3cc94c95d.png)

**Comment by pramodneyyoor** [comment]
The error is being thrown from this code:
![image](https://user-images.githubusercontent.com/36133452/65087461-c7f24f80-d983-11e9-8efe-bb5f5f3e356c.png)

**Comment by FeiChen-okta** [comment]
Hi @pramodneyyoor,

Are you able to capture the logs of the error? If you can provide a stack trace that would be helpful in troubleshooting the issue. Also are you overriding the encryption manager or using the default implementation?

**Comment by pramod-nair** [comment]
Hi @FeiChen-okta 
Thanks a lot for looking into this. Below info:

**Error stacktrace:**
09-17 15:38:43.992 29974-29974/com.unisys.fms2go D/PlainActivity: Keys are invalid. null onError Authorization error
AuthorizationException: {"type":4,"code":5003,"error":"Keys are invalid. null"}
at com.okta.oidc.util.AuthorizationException$EncryptionErrors.byEncryptionException(AuthorizationException.java:514)
at com.okta.oidc.clients.AuthAPI.obtainNewConfiguration(AuthAPI.java:87)
at com.okta.oidc.clients.web.SyncWebAuthClientImpl.signIn(SyncWebAuthClientImpl.java:213)
at com.okta.oidc.clients.web.WebAuthClientImpl.lambda$signIn$3$WebAuthClientImpl(WebAuthClientImpl.java:136)
at com.okta.oidc.clients.web.WebAuthClientImpl$$Lambda$2.run(Unknown Source:6)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

**We are not overriding the encryption. Default is being used**
		Okta.WebAuthBuilder builder = new Okta.WebAuthBuilder()
				.withConfig(mOidcConfig)
				.withContext(getApplicationContext())
				.withCallbackExecutor(null)
				.withEncryptionManager(new DefaultEncryptionManager(this)) 
				.withTabColor(0)
				.withOktaHttpClient(factory.build())
				.supportedBrowsers("com.android.chrome");

**Device:**
Samsung Galaxy S9
SM-G960U

We have a deadline to release Okta implementation this weekend. If you can help us with this  we really appreciate that. @FeiChen-okta

**Comment by FeiChen-okta** [comment]
Hi @pramodneyyoor,

I've created a branch https://github.com/okta/okta-oidc-android/tree/remove_workaround
where the encryption classes are available in the app level. See if the sample works on your device. I suspect it is due to the workaround for an issue with bouncy castle so it is removed.
What is the OS version?

**Comment by FeiChen-okta** [comment]
Issue was due to inaccessible data due to keys being invalidate either from uninstallation or changing device security.
